### ISSUE TITLE
Don't Commit To Main

### ISSUE THREAD

**Issue by kbgg** [source-cooperative/source.coop#13]
As this is now an open-source project, it's imperative that you **DO NOT** commit changes directly to main without a code review.

There are [several reasons](https://softwareengineering.stackexchange.com/questions/255944/what-is-the-purpose-of-a-code-review) why a code review should be required and it hinders collaboration on an open-source project when you do this.

Recent changes made by @navdeepg2021 were not communicated at all, directly relate to the security of the service, added new configuration parameters for deployment, and were not documented. If this had gone through the code-review process there would have at least been a discussion on why these changes should have been documented.

There is a [PR open](https://github.com/source-cooperative/source.coop/pull/11) which codifies these requirements as conditions for getting changes merged into the code base.

cc @jedsundwall @tylere

**Comment by jedsundwall** [comment]
Thanks for this, Kevin. I've reviewed and accepted the PR with the contribution guidelines. Thanks for creating those. 

@ecov-user I'll follow up with you separately to see if we can talk on Friday. As discussed on Slack, please create a dev environment so we can have an extra layer of protection when working on these changes.

**Comment by jedsundwall** [comment]
Dev environment has been created.
