### ISSUE TITLE
Unable to get s3 files in local execution

### ISSUE THREAD

**Issue by navdeepg2021** [source-cooperative/source.coop#18]
Steps:
1. Run application locally.
2. Create a new repository.
3. Add/upload a new readme file using the api keys. 
4. Try to browse the readme me file.

Unable to read this file as the file contents are empty.

**Comment by kbgg** [comment]
Please follow the bug report template as directed in the [contribution guidelines](https://github.com/source-cooperative/source.coop/blob/main/CONTRIBUTING.md#did-you-find-a-bug).
