### ISSUE TITLE
[Bug] Displayed S3 URI is incorrect

### ISSUE THREAD

**Issue by TomNicholas** [source-cooperative/source.coop#33]
**Description of Bug:**

The Browse feature of the data catalog displays the wrong S3 URI for files.

**Steps to Reproduce:**
- Go to https://source.coop/cworthy/oae-efficiency-atlas/data/experiments/000/01/alk-forcing.000-1999-01.pop.h.0347-01.nc
- See that the S3 URI says `s3://cworthy/oae-efficiency-atlas/oae-efficiency-atlas/data/experiments/000/01/alk-forcing.000-1999-01.pop.h.0347-01.nc`
- Realise that that is not a real bucket - this data file actually lives at `s3://us-west-2.opendata.source.coop/cworthy/oae-efficiency-atlas/oae-efficiency-atlas/data/experiments/000/01/alk-forcing.000-1999-01.pop.h.0347-01.nc`. The prefix is wrong.

**Expected Behavior:**

Display the correct S3 URI.

**Comment by navdeepg2021** [comment]
@TomNicholas I think its by design that since the data proxy is abstracting the real bucket involved as this s3 url is only meant to be understood by data proxy.

**Comment by TomNicholas** [comment]
Thanks for the input @navdeepg2021.

> the data proxy is abstracting the real bucket involved. This s3 url is only meant to be understood by data proxy.

What if I want to access in a way that requires knowing the actual bucket url though? Http requests to a url is just as common a way to access data as using the AWS CLI is. Without easily discovering this url users can't use tools like [fsspec](https://github.com/fsspec/filesystem_spec) or [xarray via zarr](https://docs.xarray.dev/en/stable/user-guide/io.html#cloud-storage-buckets) to get to the data.

**Comment by TomNicholas** [comment]
Okay now I've just learned about S3 endpoints, I see that I can still get to my data using `fsspec` by doing 

```python
s3fs_kwargs = {'anon': True, 'endpoint_url': 'https://data.source.coop'}
fs = s3fs.S3FileSystem(**s3fs_kwargs)

ds = xr.open_dataset(fs.open(single_file_url), engine='h5netcdf')
```

**Comment by navdeepg2021** [comment]
@TomNicholas We have resolved the issue raised as per this issue. Please check the contents of the page here, https://source.coop/cworthy/oae-efficiency-atlas/data/experiments/000/01/alk-forcing.000-1999-01.pop.h.0347-01.nc.

Can you please confirm if this is the expected scenario. The cloud uri correctly reflects the uri for accessing the contents of the file using AWS s3 cli.

**Comment by TomNicholas** [comment]
Thank you @navdeepg2021 ! That cloud URI looks like what I would expect now.
