### ISSUE TITLE
Repository settings

### ISSUE THREAD

**Issue by severo** [source-cooperative/source.coop#39]
I propose the following changes for the project setup in https://github.com/source-cooperative/source.coop/settings:
- default branch: "dev," which would allow the removal of a checkbox in the PRs ("This PR is made against the dev branch (all proposed changes except releases should be against dev, not main), or at least, reduce the possibility of errors." - https://github.com/source-cooperative/source.coop/blob/main/.github/pull_request_template.md?plain=1#L11)
- only enable "Allow squash merging" which would allow to remove a checkbox in the PRs ("This PR contains only one commit." - https://github.com/source-cooperative/source.coop/blob/main/.github/pull_request_template.md?plain=1#L13)
- check "Always suggest updating pull request branches" 
- check "Automatically delete head branches"

**Comment by jedsundwall** [comment]
Done!

- [x] default branch: "dev,"
- [x] only enable "Allow squash merging" 
- [x] check "Always suggest updating pull request branches"
- [x] check "Automatically delete head branches"

I've also edited the PR checkbox to remove the "This PR contains only one commit" checkbox. 

Please let me know if you'd like us to make any other changes, Sylvain!

**Comment by severo** [comment]
Nice, thanks!
